#!/usr/bin/env python3
"""
Setup WhatsApp API untuk Arunika Command Centre
Tanya user: provider, API key, nomor, webhook URL, lalu simpan config.
"""
import os
import sys
import json
from pathlib import Path

ACC_HOME = Path(os.environ.get("ACC_HOME", Path(__file__).resolve().parent.parent))
DATA_DIR = ACC_HOME / "data"
ENV_FILE = DATA_DIR / ".env"
CONFIG_FILE = DATA_DIR / "config.yaml"


def load_env_dict():
    """Baca .env jadi dict."""
    env_dict = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                env_dict[k.strip()] = v.strip()
    return env_dict


def save_env_dict(env_dict):
    """Simpan dict ke .env."""
    lines = ["# Auto-generated by setup-whatsapp.py\n"]
    for k, v in sorted(env_dict.items()):
        lines.append(f"{k}={v}\n")
    ENV_FILE.write_text("".join(lines), encoding="utf-8")


def test_provider(provider, api_key):
    """Test koneksi ke provider."""
    if provider == "telnyx":
        import http.client
        try:
            conn = http.client.HTTPSConnection("api.telnyx.com")
            conn.request("GET", "/v2/messages", headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json"
            })
            resp = conn.getresponse()
            ok = resp.status in (200, 400, 401)  # 401 berarti auth dicek, bukan koneksi error
            conn.close()
            return ok, f"Status {resp.status}"
        except Exception as e:
            return False, str(e)
    elif provider == "twilio":
        try:
            import base64
            auth_header = base64.b64encode(f"AC{api_key[:20]}:{api_key}".encode()).decode()
            import http.client
            conn = http.client.HTTPSConnection("api.twilio.com")
            conn.request("GET", "/2010-04-01/Accounts.json", headers={
                "Authorization": f"Basic {auth_header}"
            })
            resp = conn.getresponse()
            ok = resp.status in (200, 401)
            conn.close()
            return ok, f"Status {resp.status}"
        except Exception as e:
            return False, str(e)
    return True, "Manual verify (offline mode)"


def main():
    print("\n" + "="*50)
    print("  SETUP WhatsApp API untuk ACC")
    print("  PT. Arunika Teknologi Global")
    print("="*50 + "\n")

    # Cek apakah sudah ada setup sebelumnya
    env_dict = load_env_dict()
    if env_dict.get("WA_PROVIDER"):
        print(f"[*] Sudah ada setup WhatsApp: {env_dict.get('WA_PROVIDER')}")
        ans = input("Ubah setup? (y/n) > ").strip().lower()
        if ans != "y":
            print("Keluar tanpa perubahan.")
            return

    print("Pilih provider WhatsApp:")
    print("  [1] Telnyx (recommended — setup cepat, API clean)")
    print("  [2] Twilio (gratis sandbox, mudah testing)")
    print("  [3] Meta Cloud API (official, butuh Business Verification)")
    print("  [0] Skip setup WhatsApp (tetap gunakan chat mode saja)")

    choice = input("\nPilih (0-3) > ").strip()

    if choice == "0":
        print("✓ Setup WhatsApp dilewati. Gunakan ACC via chat mode biasa.")
        return

    provider_map = {"1": "telnyx", "2": "twilio", "3": "meta"}
    if choice not in provider_map:
        print("Pilihan tidak valid. Keluar.")
        return

    provider = provider_map[choice]
    print(f"\n[*] Setup {provider.upper()}...\n")

    # Tanya API key
    if provider == "telnyx":
        print("Daftar di: https://portal.telnyx.com")
        print("Cari API key di: Account > API Keys")
        api_key = input("\nAPI Key (SK_...) > ").strip()
        if not api_key.startswith("SK_"):
            print("⚠️  Format API key Telnyx dimulai SK_. Periksa ulang.")
    elif provider == "twilio":
        print("Daftar di: https://www.twilio.com/console")
        print("Cari Auth Token di: Account > Keys & Credentials")
        api_key = input("\nAuth Token > ").strip()
        if not api_key:
            print("Auth Token kosong.")
            return
    else:  # meta
        print("Pendaftaran Meta Business: https://developers.facebook.com/docs/business-messaging/whatsapp/")
        print("Dapatkan Phone Number ID & Access Token dari: https://developers.facebook.com/apps/")
        api_key = input("\nAccess Token > ").strip()

    if not api_key:
        print("API key kosong. Keluar.")
        return

    # Nomor WhatsApp
    phone = input("\nNomor WhatsApp Anda (62812xxxx) > ").strip().replace("-", "").replace(" ", "")
    if not phone:
        print("Nomor kosong.")
        return

    # Webhook URL
    print("\nWebhook URL (URL tempat ACC menerima pesan dari WhatsApp):")
    print("  Contoh: https://yourdomain.com/wa-webhook")
    print("         atau: https://your-ngrok-tunnel.ngrok.io/wa-webhook")
    webhook_url = input("Webhook URL > ").strip()
    if not webhook_url:
        print("Webhook URL kosong. Gunakan default lokal.")
        webhook_url = "http://localhost:5000/wa-webhook"

    # Test koneksi
    print("\n[*] Mengtest koneksi ke provider...")
    ok, msg = test_provider(provider, api_key)
    if ok:
        print(f"✓ Koneksi OK ({msg})")
    else:
        print(f"⚠️  Koneksi gagal ({msg})")
        ans = input("Lanjut tetap? (y/n) > ").strip().lower()
        if ans != "y":
            print("Setup dibatalkan.")
            return

    # Simpan ke .env
    print("\n[*] Menyimpan konfigurasi...")
    env_dict.update({
        "WA_PROVIDER": provider,
        "WA_API_TOKEN": api_key,
        "WA_PHONE_NUMBER": phone,
        "WA_WEBHOOK_URL": webhook_url,
    })
    save_env_dict(env_dict)

    # Buat/update webhook handler stub
    handler_file = ACC_HOME / "src" / "whatsapp_handler.py"
    if not handler_file.exists():
        handler_file.write_text(f'''#!/usr/bin/env python3
"""WhatsApp handler untuk ACC (auto-generated oleh setup)"""
import sys, json, os
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))

def handle_message(provider, msg_data):
    """Parse pesan dari {{provider}}, kirim ke ACC orchestrator."""
    # TODO: parse msg_data sesuai format provider
    # TODO: kirim ke queue ACC
    return {{"status": "ok"}}

if __name__ == "__main__":
    from dotenv import load_dotenv
    load_dotenv()
    print(f"WhatsApp handler siap untuk {{os.environ.get('WA_PROVIDER')}}")
    print("Integrasikan ke launcher untuk menerima pesan real-time.")
''', encoding="utf-8")

    print("✓ data/.env updated")
    print(f"✓ Webhook handler: {handler_file}")

    # Info langkah berikutnya
    print("\n" + "="*50)
    print("  ✓ Setup WhatsApp selesai!")
    print("="*50)
    print(f"""
Provider     : {provider.upper()}
Phone        : {phone}
Webhook      : {webhook_url}

Langkah berikutnya:
1. Daftar webhook Anda di dashboard provider
   Telnyx: Manage > Messaging > Webhooks
   Twilio: Messaging > Services > Webhooks
   
2. Verify webhook (provider akan POST ke URL Anda)

3. Jalankan ACC dan kirim pesan dari WhatsApp

4. Pesan akan masuk → ACC proses → balas ke WhatsApp

Tips:
- Untuk testing lokal, gunakan ngrok: ngrok http 5000
  Webhook URL: https://xxxx.ngrok.io/wa-webhook
  
- Untuk production, gunakan domain/server public

- Cek logs di: data/sessions/

Dokumentasi:
  Telnyx:  https://developers.telnyx.com/docs/messaging/whatsapp-api
  Twilio:  https://www.twilio.com/docs/whatsapp/api
  Meta:    https://developers.facebook.com/docs/whatsapp/cloud-api/
""")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup dibatalkan.")
        sys.exit(1)
